// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using police_poll_service.DB;

#nullable disable

namespace police_poll_service.Migrations
{
    [DbContext(typeof(PolicePollDbContext))]
    partial class PolicePollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("police_poll_service.DB.Tables.CONFIG", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("config");
                });

            modelBuilder.Entity("police_poll_service.DB.Tables.EVALUATION", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("crime_prevention_work_count")
                        .HasColumnType("int");

                    b.Property<decimal>("crime_prevention_work_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("evaluation_year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("evaluators_amount")
                        .HasColumnType("int");

                    b.Property<int>("investigative_work_count")
                        .HasColumnType("int");

                    b.Property<decimal>("investigative_work_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("org_unit_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("satisfaction_count")
                        .HasColumnType("int");

                    b.Property<decimal>("satisfaction_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("service_work_count")
                        .HasColumnType("int");

                    b.Property<decimal>("service_work_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("traffic_work_count")
                        .HasColumnType("int");

                    b.Property<decimal>("traffic_work_score")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("evaluation");
                });

            modelBuilder.Entity("police_poll_service.DB.Tables.ORG_UNIT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("crime_prevention_work_total")
                        .HasColumnType("int");

                    b.Property<string>("evaluation_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("evaluators_total")
                        .HasColumnType("int");

                    b.Property<string>("head_org_unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("investigative_work_total")
                        .HasColumnType("int");

                    b.Property<bool>("is_evaluation")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("satisfaction_total")
                        .HasColumnType("int");

                    b.Property<int>("service_work_total")
                        .HasColumnType("int");

                    b.Property<int>("traffic_work_total")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("org_unit");
                });

            modelBuilder.Entity("police_poll_service.DB.Tables.ROLE", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("police_poll_service.DB.Tables.USER", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("org_unit_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
